### ISSUE TITLE
Altitude dial spins the wrong way when decreasing

### ISSUE THREAD

**Issue by sekjun9878** [SirDiazo/LandingHeight#2]
Hello,

For example, when the altitude goes from 285 to 275, instead of cleanly going from the dial '8' to the dial '7', the plugin seems to go from '8', '9', '0', ..., and then to '7'.

**Comment by SirDiazo** [comment]
Not fixable unfortunately.

All this mod does is intercept the value being sent to the altimeter at the top of the screen and replace it with a different value, I don't actually touch the UI display widget in any way so to fix that Squad would have to change how the on-screen UI display worked.

As they are actually overhauling the entire UI for KSP 1.1 to use an entirely new system it is quite probable this will be fixed in the next KSP version. However it depends on what Squad does, there's nothing I can do about this.
